Config = {}
Config.RefreshRate = 1
Config.Prompts = {
    PromptPhoto = 0x07B8BEAF,
    PromptStart = 0xF84FA74F,
    PromptAlbum = 0xC7B5340A,
    PromptExit = 0x05CA7C52,
    PromptZoom1 = 0xF78D7337,
    PromptZoom2 = 0xD0842EDF,
    PromptFilter1 = 0xDEB34313,
    PromptFilter2 = 0xA65EBAB4,
}

Config.Texts = {
    PromptPhoto = "Take Photo",
    PromptStart = "Start",
    PromptAlbum = "View Photos",
    PromptExit = "Exit",
    PromptZoom1 = "Zoom In", 
    PromptZoom2 = "Zoom Out",
    PromptFilter1 = "Next Filter",
    PromptFilter2 = "Prev Filter",
    --
    Camera = "Camera",
}

Config.MaxZoom = {
    [`weapon_kit_camera`] = 5,
    [`weapon_kit_camera_advanced`] = 10,
}

Config.CameraFXs = {
    [`weapon_kit_camera`] = {
        "PhotoMode_Bounds",
        "CameraViewfinder",
    },
    [`weapon_kit_camera_advanced`] = {
        "PhotoMode_Bounds",
        "CameraViewfinder",
    },
}

Config.CameraFilters = {
    [`weapon_kit_camera`] = {
        {'PhotoMode_FilterGame01', ''},
        {'PhotoMode_FilterGame02', ''},
        {'PhotoMode_FilterGame03', ''},
        {'PhotoMode_FilterGame04', ''},
        {'PhotoMode_FilterGame05', ''},
        {'PhotoMode_FilterGame06', ''},
        {'PhotoMode_FilterGame07', ''},
        {'PhotoMode_FilterGame08', ''},
        {'PhotoMode_FilterGame09', ''},
        {'PhotoMode_FilterGame10', ''},
        {'PhotoMode_FilterModern01', ''},
        {'PhotoMode_FilterModern02', ''},
        {'PhotoMode_FilterModern03', ''},
        {'PhotoMode_FilterModern04', ''},
        {'PhotoMode_FilterModern05', ''},
        {'PhotoMode_FilterModern06', ''},
        {'PhotoMode_FilterModern07', ''},
        {'PhotoMode_FilterModern08', ''},
        {'PhotoMode_FilterModern09', ''},
        {'PhotoMode_FilterModern10', ''},
        {'PhotoMode_FilterVintage01', ''},
        {'PhotoMode_FilterVintage02', ''},
        {'PhotoMode_FilterVintage03', ''},
        {'PhotoMode_FilterVintage04', ''},
        {'PhotoMode_FilterVintage05', ''},
        {'PhotoMode_FilterVintage06', ''},
        {'PhotoMode_FilterVintage07', ''},
        {'PhotoMode_FilterVintage08', ''},
        {'PhotoMode_FilterVintage09', ''},
        {'PhotoMode_FilterVintage10', ''},
        {'PhotoMode_FilterGame11', ''},
        {'PhotoMode_FilterGame12', ''},
        {'PhotoMode_FilterGame13', ''},
        {'PhotoMode_FilterGame14', ''},
        {'PhotoMode_FilterGame15', ''},
        {'PhotoMode_FilterGame16', ''},
        {'PhotoMode_FilterGame17', ''},
        {'PhotoMode_FilterGame18', ''},
    },
    [`weapon_kit_camera_advanced`] = {
        {'PhotoMode_FilterGame01', 'Filter Label 1'},
        {'PhotoMode_FilterGame02', ''},
        {'PhotoMode_FilterGame03', ''},
        {'PhotoMode_FilterGame04', ''},
        {'PhotoMode_FilterGame05', ''},
        {'PhotoMode_FilterGame06', ''},
        {'PhotoMode_FilterGame07', ''},
        {'PhotoMode_FilterGame08', ''},
        {'PhotoMode_FilterGame09', ''},
        {'PhotoMode_FilterGame10', ''},
        {'PhotoMode_FilterModern01', ''},
        {'PhotoMode_FilterModern02', ''},
        {'PhotoMode_FilterModern03', ''},
        {'PhotoMode_FilterModern04', ''},
        {'PhotoMode_FilterModern05', ''},
        {'PhotoMode_FilterModern06', ''},
        {'PhotoMode_FilterModern07', ''},
        {'PhotoMode_FilterModern08', ''},
        {'PhotoMode_FilterModern09', ''},
        {'PhotoMode_FilterModern10', ''},
        {'PhotoMode_FilterVintage01', ''},
        {'PhotoMode_FilterVintage02', ''},
        {'PhotoMode_FilterVintage03', ''},
        {'PhotoMode_FilterVintage04', ''},
        {'PhotoMode_FilterVintage05', ''},
        {'PhotoMode_FilterVintage06', ''},
        {'PhotoMode_FilterVintage07', ''},
        {'PhotoMode_FilterVintage08', ''},
        {'PhotoMode_FilterVintage09', ''},
        {'PhotoMode_FilterVintage10', ''},
        {'PhotoMode_FilterGame11', ''},
        {'PhotoMode_FilterGame12', ''},
        {'PhotoMode_FilterGame13', ''},
        {'PhotoMode_FilterGame14', ''},
        {'PhotoMode_FilterGame15', ''},
        {'PhotoMode_FilterGame16', ''},
        {'PhotoMode_FilterGame17', ''},
        {'PhotoMode_FilterGame18', ''},
    },
}

